#!/usr/bin/env perl

use strict;
use warnings;

use Capture::Tiny 'capture_merged';
use Process::Status;

my $body = do { local $/; <STDIN> };

die "$body does not start with remind me to\n"
  unless $body =~ m/^remind me to (.+) at (.+)$/i;

my $message = $1;
my $timespec = $2;

# TODO: exit non-zero if the command does
my $out = capture_merged {
  open(my $ph, '|-', 'at', $timespec);
  print $ph "./bin/action-pushover $message";
};

$out =~ s(warning: commands will be executed using /bin/sh\n)();

print $out
